
import type { AppState, TrendingTimeRange } from '../types';
import { defaultHeaderMenuConfig, defaultReleaseSourceSettings, defaultSubscriptionChannels } from '../types';
import { defaultRepositoryChatSettings } from '../types/repositoryChat';
import { DEFAULT_THEME_PRESET_ID } from '../constants/themePresets';
import { DEFAULT_XTWEET_FEED_BASE_URL, DEFAULT_XTWEET_FOLLOWS } from '../utils/xTweetFollows';
import { readSessionBackendSecret } from './persistence/authStorage';
import {
  defaultDiscoveryChannels,
  defaultMcpConfig,
  defaultPresetFilters,
  defaultVectorSearchConfig,
  defaultVectorSearchStatus,
  initialGistSearchFilters,
  initialSearchFilters,
} from './schema';

export const createInitialState = (): AppState => ({
      // Initial state
      user: null,
      githubToken: null,
      isAuthenticated: false,
      repositories: [],
      gists: [],
      starredGists: [],
      gistSearchFilters: initialGistSearchFilters,
      gistSearchResults: [],
      selectedGistCategory: 'all',
      analyzingGistIds: new Set<string>(),
      isLoading: false,
      isSyncingStars: false,
      lastSync: null,
      syncMode: 'stars',
      syncModeConfigured: false,
      listsPush: { isRunning: false, total: 0, done: 0, currentLabel: null, message: null, error: null },
      categoryListIdMap: {},
      analyzingRepositoryIds: new Set<number>(),
      aiConfigs: [],
      activeAIConfig: null,
      repositoryChatSettings: { ...defaultRepositoryChatSettings },
      embeddingConfigs: [],
      activeEmbeddingConfig: null,
      vectorSearchConfig: { ...defaultVectorSearchConfig },
      vectorSearchStatus: { ...defaultVectorSearchStatus },
      vectorIndexingState: { isIndexing: false, phase: null, phaseDone: 0, phaseTotal: 0, result: null },
      mcpConfig: { ...defaultMcpConfig },
      similarView: null,
      webdavConfigs: [],
      activeWebDAVConfig: null,
      lastBackup: null,
      searchFilters: initialSearchFilters,
      searchResults: [],
      releases: [],
      releaseSubscriptions: new Set<number>(),
      releaseSourceSettings: defaultReleaseSourceSettings,
      readReleases: new Set<number>(),
      customCategories: [],
      hiddenDefaultCategoryIds: [],
      defaultCategoryOverrides: {},
      categoryOrder: [],
      collapsedSidebarCategoryCount: 20,
      categoryMatchMode: 'effective',
      assetFilters: defaultPresetFilters,
      theme: 'dark',
      themePreset: DEFAULT_THEME_PRESET_ID,
      hasHydrated: false,
      currentView: 'repositories',
      selectedCategory: 'all',
      language: 'zh',
      translationEngine: 'microsoft',
      updateNotification: null,
      analysisProgress: { current: 0, total: 0 },
      backendApiSecret: readSessionBackendSecret(),
      proxyConfig: { enabled: false, type: 'http', host: '', port: 7890 },
      rpcDownloadConfig: { enabled: false, host: '', port: 6800 },
      routeMode: 'auto',
      isSidebarCollapsed: false,
      readmeModalOpen: false,
      repositoryViewMode: 'grid',
      releaseViewMode: 'timeline',
      releaseShowMode: 'all',
      releaseLatestMode: 'all',
      releaseSelectedFilters: [],
      releaseSearchQuery: '',
      releaseExpandedRepositories: new Set<number>(),
      releaseIsRefreshing: false,
      includePreRelease: true,
      includeKeysInBackup: false,

      forks: [],
      readForks: new Set<number>(),
      forkViewMode: 'timeline',
      forkSelectedFilters: [],
      forkSearchQuery: '',
      forkExpandedRepositories: new Set<number>(),
      forkIsRefreshing: false,

      discoveryChannels: defaultDiscoveryChannels,
      discoveryRepos: { 'trending': [], 'hot-release': [], 'most-popular': [], 'topic': [], 'x-tweet': [], 'weekly': [], 'search': [], 'code-search': [] },
      discoveryLastRefresh: { 'trending': null, 'hot-release': null, 'most-popular': null, 'topic': null, 'x-tweet': null, 'weekly': null, 'search': null, 'code-search': null },
      discoveryIsLoading: { 'trending': false, 'hot-release': false, 'most-popular': false, 'topic': false, 'x-tweet': false, 'weekly': false, 'search': false, 'code-search': false },
      discoveryIsLoadingMore: { 'trending': false, 'hot-release': false, 'most-popular': false, 'topic': false, 'x-tweet': false, 'weekly': false, 'search': false, 'code-search': false },
      discoveryLoadMoreError: { 'trending': null, 'hot-release': null, 'most-popular': null, 'topic': null, 'x-tweet': null, 'weekly': null, 'search': null, 'code-search': null },
      selectedDiscoveryChannel: 'trending',
      discoveryPlatform: 'All',
      discoveryLanguage: 'All',
      discoverySortBy: 'BestMatch',
      discoverySortOrder: 'Descending',
      discoverySearchQuery: '',
      discoverySelectedTopic: null,
      discoveryHasMore: { 'trending': false, 'hot-release': false, 'most-popular': false, 'topic': false, 'x-tweet': false, 'weekly': false, 'search': false, 'code-search': false },
      discoveryNextPage: { 'trending': 1, 'hot-release': 1, 'most-popular': 1, 'topic': 1, 'x-tweet': 1, 'weekly': 1, 'search': 1, 'code-search': 1 },
      discoveryTotalCount: { 'trending': 0, 'hot-release': 0, 'most-popular': 0, 'topic': 0, 'x-tweet': 0, 'weekly': 0, 'search': 0, 'code-search': 0 },
      discoveryScrollPositions: { 'trending': 0, 'hot-release': 0, 'most-popular': 0, 'topic': 0, 'x-tweet': 0, 'weekly': 0, 'search': 0, 'code-search': 0 },
  trendingTimeRange: 'weekly' as TrendingTimeRange,
      weeklyOnlyCollected: false,
      weeklySyncStatus: null,
      xTweetFollows: DEFAULT_XTWEET_FOLLOWS.map((follow) => ({ ...follow })),
      xTweetFeedBaseUrl: DEFAULT_XTWEET_FEED_BASE_URL,
      xTweetSyncStatus: null,

      // Subscription
      subscriptionRepos: { 'most-stars': [], 'most-forks': [], 'most-dev': [], 'trending': [] },
      subscriptionLastRefresh: { 'most-stars': null, 'most-forks': null, 'most-dev': null, 'trending': null },
      subscriptionIsLoading: { 'most-stars': false, 'most-forks': false, 'most-dev': false, 'trending': false },
      subscriptionChannels: defaultSubscriptionChannels,
      headerMenuConfig: defaultHeaderMenuConfig,
});
