import type { AppStoreState } from './types';

/**
 * Domain selectors intentionally return only the state and actions a caller
 * renders or invokes. Consumers must wrap aggregate selectors with
 * `useShallow` so unrelated Store changes retain the previous selection.
 */
export const selectAppShellState = (state: AppStoreState) => ({
  isAuthenticated: state.isAuthenticated,
  currentView: state.currentView,
  selectedCategory: state.selectedCategory,
  theme: state.theme,
  themePreset: state.themePreset,
  hasHydrated: state.hasHydrated,
  searchResults: state.searchResults,
  searchFilters: state.searchFilters,
  repositories: state.repositories,
  setSelectedCategory: state.setSelectedCategory,
});

export const selectAuthSession = (state: AppStoreState) => ({
  user: state.user,
  githubToken: state.githubToken,
  isAuthenticated: state.isAuthenticated,
  hasHydrated: state.hasHydrated,
});

export const selectRepositoryListState = (state: AppStoreState) => ({
  repositories: state.repositories,
  searchResults: state.searchResults,
  searchFilters: state.searchFilters,
  selectedCategory: state.selectedCategory,
  repositoryViewMode: state.repositoryViewMode,
  language: state.language,
});

export const selectPreferenceState = (state: AppStoreState) => ({
  language: state.language,
  theme: state.theme,
  themePreset: state.themePreset,
  currentView: state.currentView,
  selectedCategory: state.selectedCategory,
  isSidebarCollapsed: state.isSidebarCollapsed,
});

export const selectReleaseTimelineState = (state: AppStoreState) => ({
  releases: state.releases,
  repositories: state.repositories,
  releaseSubscriptions: state.releaseSubscriptions,
  releaseSourceSettings: state.releaseSourceSettings,
  readReleases: state.readReleases,
  githubToken: state.githubToken,
  language: state.language,
  assetFilters: state.assetFilters,
  addReleases: state.addReleases,
  upsertReleases: state.upsertReleases,
  markReleaseAsRead: state.markReleaseAsRead,
  markAssetAsRead: state.markAssetAsRead,
  markAllReleasesAsRead: state.markAllReleasesAsRead,
  batchUnsubscribeReleases: state.batchUnsubscribeReleases,
  removeReleasesByRepoFullName: state.removeReleasesByRepoFullName,
  updateRepository: state.updateRepository,
  removeReleaseSourceRepository: state.removeReleaseSourceRepository,
  updateReleaseSourceRepository: state.updateReleaseSourceRepository,
  releaseViewMode: state.releaseViewMode,
  releaseSelectedFilters: state.releaseSelectedFilters,
  releaseSearchQuery: state.releaseSearchQuery,
  releaseExpandedRepositories: state.releaseExpandedRepositories,
  releaseIsRefreshing: state.releaseIsRefreshing,
  setReleaseViewMode: state.setReleaseViewMode,
  toggleReleaseSelectedFilter: state.toggleReleaseSelectedFilter,
  clearReleaseSelectedFilters: state.clearReleaseSelectedFilters,
  setReleaseSearchQuery: state.setReleaseSearchQuery,
  toggleReleaseExpandedRepository: state.toggleReleaseExpandedRepository,
  setReleaseIsRefreshing: state.setReleaseIsRefreshing,
  includePreRelease: state.includePreRelease,
  setIncludePreRelease: state.setIncludePreRelease,
  releaseShowMode: state.releaseShowMode,
  setReleaseShowMode: state.setReleaseShowMode,
  releaseLatestMode: state.releaseLatestMode,
  setReleaseLatestMode: state.setReleaseLatestMode,
});

export const selectForkTimelineState = (state: AppStoreState) => ({
  user: state.user,
  forks: state.forks,
  readForks: state.readForks,
  githubToken: state.githubToken,
  language: state.language,
  markForkAsRead: state.markForkAsRead,
  forkSearchQuery: state.forkSearchQuery,
  forkIsRefreshing: state.forkIsRefreshing,
  setForkSearchQuery: state.setForkSearchQuery,
  setForkIsRefreshing: state.setForkIsRefreshing,
});

export const selectGistViewState = (state: AppStoreState) => ({
  user: state.user,
  githubToken: state.githubToken,
  gists: state.gists,
  starredGists: state.starredGists,
  gistSearchFilters: state.gistSearchFilters,
  gistSearchResults: state.gistSearchResults,
  selectedGistCategory: state.selectedGistCategory,
  aiConfigs: state.aiConfigs,
  activeAIConfig: state.activeAIConfig,
  language: state.language,
  setGists: state.setGists,
  setStarredGists: state.setStarredGists,
  updateGist: state.updateGist,
  deleteGist: state.deleteGist,
  setGistSearchFilters: state.setGistSearchFilters,
  setGistSearchResults: state.setGistSearchResults,
  setSelectedGistCategory: state.setSelectedGistCategory,
  setAnalyzingGist: state.setAnalyzingGist,
});

export const selectDiscoveryViewState = (state: AppStoreState) => ({
  githubToken: state.githubToken,
  language: state.language,
  discoveryChannels: state.discoveryChannels,
  discoveryRepos: state.discoveryRepos,
  discoveryLastRefresh: state.discoveryLastRefresh,
  discoveryIsLoading: state.discoveryIsLoading,
  discoveryIsLoadingMore: state.discoveryIsLoadingMore,
  discoveryLoadMoreError: state.discoveryLoadMoreError,
  selectedDiscoveryChannel: state.selectedDiscoveryChannel,
  setSelectedDiscoveryChannel: state.setSelectedDiscoveryChannel,
  setDiscoveryLoading: state.setDiscoveryLoading,
  setDiscoveryLoadingMore: state.setDiscoveryLoadingMore,
  setDiscoveryLoadMoreError: state.setDiscoveryLoadMoreError,
  setDiscoveryRepos: state.setDiscoveryRepos,
  setDiscoveryLastRefresh: state.setDiscoveryLastRefresh,
  updateDiscoveryRepo: state.updateDiscoveryRepo,
  aiConfigs: state.aiConfigs,
  activeAIConfig: state.activeAIConfig,
  analysisProgress: state.analysisProgress,
  setAnalysisProgress: state.setAnalysisProgress,
  discoveryPlatform: state.discoveryPlatform,
  setDiscoveryPlatform: state.setDiscoveryPlatform,
  discoveryLanguage: state.discoveryLanguage,
  setDiscoveryLanguage: state.setDiscoveryLanguage,
  discoverySortBy: state.discoverySortBy,
  setDiscoverySortBy: state.setDiscoverySortBy,
  discoverySortOrder: state.discoverySortOrder,
  setDiscoverySortOrder: state.setDiscoverySortOrder,
  discoverySearchQuery: state.discoverySearchQuery,
  setDiscoverySearchQuery: state.setDiscoverySearchQuery,
  discoverySelectedTopic: state.discoverySelectedTopic,
  setDiscoverySelectedTopic: state.setDiscoverySelectedTopic,
  discoveryHasMore: state.discoveryHasMore,
  setDiscoveryHasMore: state.setDiscoveryHasMore,
  discoveryNextPage: state.discoveryNextPage,
  setDiscoveryNextPage: state.setDiscoveryNextPage,
  discoveryTotalCount: state.discoveryTotalCount,
  setDiscoveryTotalCount: state.setDiscoveryTotalCount,
  setDiscoveryScrollPosition: state.setDiscoveryScrollPosition,
  appendDiscoveryRepos: state.appendDiscoveryRepos,
  trendingTimeRange: state.trendingTimeRange,
  setTrendingTimeRange: state.setTrendingTimeRange,
  weeklyOnlyCollected: state.weeklyOnlyCollected,
  weeklySyncStatus: state.weeklySyncStatus,
  setWeeklyOnlyCollected: state.setWeeklyOnlyCollected,
  xTweetFollows: state.xTweetFollows,
  xTweetFeedBaseUrl: state.xTweetFeedBaseUrl,
  xTweetSyncStatus: state.xTweetSyncStatus,
  setXTweetSyncStatus: state.setXTweetSyncStatus,
  addXTweetFollow: state.addXTweetFollow,
  removeXTweetFollow: state.removeXTweetFollow,
  setXTweetFeedBaseUrl: state.setXTweetFeedBaseUrl,
});
